<a href="https://colab.research.google.com/github/LuisAL79/Mincursos-e-Modulos/blob/main/Modulo_I_Aula_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
s = np.array( [ 1, 2, 3] )
s

array([1, 2, 3])

In [ ]:
sc = np.array(
    [
        [1], [2] , [3]
    ]
)
sc

array([[1],
       [2],
       [3]])

In [ ]:
s*0.5

array([0.5, 1. , 1.5])

In [ ]:
sc**2

array([[1],
       [4],
       [9]])

In [ ]:
Mm = np.array(
    [
        [3,8,5],
     [0,2,8],
     [-8,25,9]
    ]
)
Mm

array([[ 3,  8,  5],
       [ 0,  2,  8],
       [-8, 25,  9]])

# Divisão de intervalos

In [ ]:
c = np.arange(5.5)
c

array([0., 1., 2., 3., 4., 5.])

In [ ]:
cp = np.arange(-2,12,3)
cp

array([-2,  1,  4,  7, 10])

In [ ]:
ll = np.linspace(-1,25)
ll

array([-1.        , -0.46938776,  0.06122449,  0.59183673,  1.12244898,
        1.65306122,  2.18367347,  2.71428571,  3.24489796,  3.7755102 ,
        4.30612245,  4.83673469,  5.36734694,  5.89795918,  6.42857143,
        6.95918367,  7.48979592,  8.02040816,  8.55102041,  9.08163265,
        9.6122449 , 10.14285714, 10.67346939, 11.20408163, 11.73469388,
       12.26530612, 12.79591837, 13.32653061, 13.85714286, 14.3877551 ,
       14.91836735, 15.44897959, 15.97959184, 16.51020408, 17.04081633,
       17.57142857, 18.10204082, 18.63265306, 19.16326531, 19.69387755,
       20.2244898 , 20.75510204, 21.28571429, 21.81632653, 22.34693878,
       22.87755102, 23.40816327, 23.93877551, 24.46938776, 25.        ])

In [ ]:
lg = np.linspace(-1,25,10)
lg

array([-1.        ,  1.88888889,  4.77777778,  7.66666667, 10.55555556,
       13.44444444, 16.33333333, 19.22222222, 22.11111111, 25.        ])

In [ ]:
np.set_printoptions(suppress=True)

ep = np.array(
    [1,5,3,58,-85,10.8,25.3,0.01,-0.001,38,-2,0.25,-0.025,10],dtype=float
)
ep.sort() # Ordena os valores
ep

array([-85.   ,  -2.   ,  -0.025,  -0.001,   0.01 ,   0.25 ,   1.   ,
         3.   ,   5.   ,  10.   ,  10.8  ,  25.3  ,  38.   ,  58.   ])

In [ ]:
ff = ep > 5
ff

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True])

In [ ]:
ep[ff]

array([10. , 10.8, 25.3, 38. , 58. ])

In [ ]:
ep.max()

58.0

In [ ]:
ep.min()

-85.0

In [ ]:
Mm

array([[ 3,  8,  5],
       [ 0,  2,  8],
       [-8, 25,  9]])

In [ ]:
# Somar colunas
Mm.sum(axis=0)

array([-5, 35, 22])

In [ ]:
# Somar linhas
Mm.sum(axis=1)

array([16, 10, 26])

# Produto escalar

In [ ]:
v1 = np.array(
    [
        [-8,6,9]
    ]
)
v1

array([[-8,  6,  9]])

In [ ]:
v2 = np.array(
    [
        [3,2,45]
    ]
)
v2

array([[ 3,  2, 45]])

In [ ]:
vd = np.vdot(v1,v2)
vd

393

# Álgebra Linear

In [ ]:
m2 = np.array(
    [
        [-2,9],
     [6,0.6]
    ]
)
m2

array([[-2. ,  9. ],
       [ 6. ,  0.6]])

Inversa

In [ ]:
m2inv = np.linalg.inv(m2)
m2inv

array([[-0.01086957,  0.16304348],
       [ 0.10869565,  0.03623188]])

In [ ]:
ident = np.matmul(m2,m2inv)
ident

array([[1., 0.],
       [0., 1.]])

In [ ]:
m2 @ m2inv

array([[1., 0.],
       [0., 1.]])

# Autovalores Autovetores

In [ ]:
m3 = np.array(
    [
        [2,5,9],
     [89,56,0],
     [-5,-6,-3]
    ]
)
m3

array([[ 2,  5,  9],
       [89, 56,  0],
       [-5, -6, -3]])

In [ ]:
sol = np.linalg.eig(m3)
sol

(array([62.10530498, -9.3270968 ,  2.22179182]),
 array([[-0.06811708, -0.56725233,  0.46473493],
        [-0.99297582,  0.77281036, -0.76911095],
        [ 0.09674235,  0.28458558,  0.43873658]]))

In [ ]:
# autovalores
sol[0]

array([62.10530498, -9.3270968 ,  2.22179182])

In [ ]:
# auto vetores normalizados
sol[1]

array([[-0.06811708, -0.56725233,  0.46473493],
       [-0.99297582,  0.77281036, -0.76911095],
       [ 0.09674235,  0.28458558,  0.43873658]])

$$\hat{A}V=\lambda V$$

# Determinante

In [ ]:
dm3 = np.linalg.det(m3)
dm3

-1287.0000000000005

# Traço

In [ ]:
tm3 = np.trace(m3)
tm3

55

In [ ]:
m3

array([[ 2,  5,  9],
       [89, 56,  0],
       [-5, -6, -3]])

## **Sistemas de Equações**

\begin{array}{lc}
   x+y+z&= 6 \\
   x+2y+2z& = 9 \\
   2x+y+3z& = 11
\end{array}

Pode ser escrito como : $$\hat{A}X=U$$

$$\displaystyle \left( \begin{array}{c} 1 & 1 & 1 \\
   1 & 2 & 2 \\
   2 & 1 & 3 \end{array} \right)\left( \begin{array}{c} x \\
   y \\
   z \end{array} \right) = \left( \begin{array}{c} 6 \\
   9 \\
   11 \end{array} \right) $$

Solução do sistema: $$X=\hat{A}^{-1}U$$

In [ ]:
A=np.array(
    [
        [1,1,1],
     [1,2,2],
     [2,1,3]
    ]
)
A

array([[1, 1, 1],
       [1, 2, 2],
       [2, 1, 3]])

In [ ]:
U=np.array(
    [[6],[9],[11]]
)
U

array([[ 6],
       [ 9],
       [11]])

In [ ]:
X=np.linalg.inv(A) @ U
X

array([[3.],
       [2.],
       [1.]])